# Generated by Django 4.0.1 on 2022-02-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podomarket', '0004_post_is_sold_alter_post_item_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, upload_to='item_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, upload_to='item_pics'),
        ),
    ]
